# Generated by Django 5.2.18 on 2026-10-09 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], max_length=20)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('beige', 'Beige'), ('brown', 'Brown'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], max_length=20)),
                ('material', models.CharField(blank=True, choices=[('cotton', 'Cotton'), ('denim', 'Denim'), ('linen', 'Linen'), ('polyester', 'Polyester'), ('wool', 'Wool'), ('rayon', 'Rayon'), ('viscose', 'Viscose'), ('silk', 'Silk'), ('satin', 'Satin'), ('knit', 'Knit'), ('chiffon', 'Chiffon'), ('leather', 'Leather')], max_length=50)),
                ('status', models.CharField(choices=[('ready', 'Ready to Wear'), ('washing', 'In the Wash')], default='ready', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
