# Generated by Django 5.2.18 on 2026-10-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('outerwear', 'Outerwear'), ('dresses', 'Dresses')], max_length=20),
        ),
    ]
