# Generated by Django 5.2.18 on 2026-10-08 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_persona', models.CharField(default='The Conscious Minimalist', max_length=100)),
                ('preferred_style', models.CharField(blank=True, max_length=50)),
                ('conscious_shopping_priority', models.CharField(blank=True, max_length=50)),
                ('wardrobe_goal', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
